### ISSUE TITLE
this needs to be updated for pynn 0.8 for the workshop

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/IntroLab#5]
^
          |
title-----

**Comment by Christian-B** [comment]
I am update so they are working ish in pynn7.

There is a database issue with sudoko which I prefer to have fixed before doing the pynn8 conversion.

**Comment by alan-stokes** [comment]
donal is on the job for the database issue.

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/IntroLab/pull/10
